### PR TITLE
[README.md] Document availability of Arch Linux package

### PR DESCRIPTION
**Pull request by alerque**

### CODE REVIEW

**Comment by chrissimpkins** [comment]
Wow, thanks so much Caleb!  I really appreciate it.  Out of interest, this is a source install that launches as a Python executable and does not use PyInstaller to embed the Py interpreter and all dependencies in a compiled executable correct?  Arch / Manjaro and the like users can simply execute `slice` in a terminal to launch the application?

 In general, is the Python source distribution approach the best way to distribute across Linux distros?  If so, does this integrate into application menus and add icons if/when users want that kind of thing?  I've got zilch experience packaging for Linux.  Apologies for all of the questions. :)

**Comment by alerque** [comment]
> Out of interest, this is a source install that launches as a Python executable and does not use PyInstaller to embed the Py interpreter and all dependencies in a compiled executable correct?

Correct, pyinstaller is not used and the system automatically supplies the Python interpreter and dependencies from other packages. This is the traditionally approach for Arch and most other distros, although some have started preferring containerized app installs that bundle dependencies. Arch and many others specifically eschew that approach. Even things like Electron apps are typically packaged by extracting the app itself and using the system supplied Electron.

This will work most of the time, although it's possible for versioning to become an issue. Arch is a rolling release and stays *very* fresh, so as long as your project does too there is rarely a conflict. If you ever stop updating to be compatible with the latest Python dependencies this package could stop working. Usually what happens then is either the distro package needs to patch it to work with new libraries or package extra "old" versions of the dependencies that do work.

> Arch / Manjaro and the like users can simply execute `slice` in a terminal to launch the application?

Close. The executable getting installed is `slicegui`. That's determined somewhere in the Python setup on your end though, not in the packaging. I thought about renaming it `slice` as part of the packaging. It would be possible to call it `slice` as that name is broadly available right now, but then I thought it would be better to stick with the upstream default naming unless there was a reason not to.

**Comment by alerque** [comment]
It's probably this line's fault that running this means typing `slicegui`:

https://github.com/source-foundry/Slice/blob/6962045d7278c2c64f95a92fbc4fd6de0bd95c9b/setup.py#L9

**Comment by chrissimpkins** [comment]
> It's probably this line's fault that running this means typing `slicegui`:
> 
> https://github.com/source-foundry/Slice/blob/6962045d7278c2c64f95a92fbc4fd6de0bd95c9b/setup.py#L9

Yes this is no problem at all.  Sorry my fault.  I did know that you were using setup.py in the package.  I needed to add the `gui` string because there is already a PyPI package named `slice`.

**Comment by chrissimpkins** [comment]
> > Out of interest, this is a source install that launches as a Python executable and does not use PyInstaller to embed the Py interpreter and all dependencies in a compiled executable correct?
> 
> Correct, PyInstaller is not used and the system automatically supplies the Python interpreter and dependencies from other packages. This is the traditionally approach for Arch and most other distros, although some have started preferring containerized app installs that bundle dependencies. Arch and many others specifically eschew that approach. Even things like Electron apps are typically packaged by extracting the app itself and using the system supplied Electron.
> 
> This will work most of the time, although it's possible for versioning to become an issue. Arch is a rolling release and stays _very_ fresh, so as long as your project does too there is rarely a conflict. If you ever stop updating to be compatible with the latest Python dependencies this package could stop working. Usually what happens then is either the distro package needs to patch it to work with new libraries or package extra "old" versions of the dependencies that do work.
> 
> > Arch / Manjaro and the like users can simply execute `slice` in a terminal to launch the application?
> 
> Close. The executable getting installed is `slicegui`. That's determined somewhere in the Python setup on your end though, not in the packaging. I thought about renaming it `slice` as part of the packaging. It would be possible to call it `slice` as that name is broadly available right now, but then I thought it would be better to stick with the upstream default naming unless there was a reason not to.

Thanks for all of this info.  That is extremely helpful Caleb.  The only potential issue that I can see with deps right now is that PyInstaller is using a dev branch so that I can work with cPy beyond 3.7.  It's not clear to me why this hasn't landed in a PyInstaller release yet but the issue is avoided altogether in your package.  cPy3.6+ is a fontTools dependency requirement that should be recursively pulled in by the fontTools package that you are using.  I *think* that we are ok.  I'll keep an eye out for dep changes that might break things in the package.  Fortunately for the GUI tooling environment, tip of the spear is frequently unsupported so I don't know that this will be as much of an issue as trailing dependency versions in a distro like Arch.

**Pull request merged**
